const intialState = {
  product: { data: [], loading: true, error: null },
  overview: {
    productStyles: { styles: {}, loading: true, error: null },
    selectDataStyle: { selected: {}, loading: true, error: null },
    selectImg: { img: {}, loading: true, error: null },
  },
  questionsAnswers: {
    main: { questions: [], loading: true, error: null },
    search: { text: '' },
  },
  ratingsReviews: {
    reviewViewLength: 2,
    reviews: {
      product: '40353',
      page: 0,
      count: 1000,
      results: [
        {
          review_id: 841525,
          rating: 5,
          summary: 'I AM THANOS',
          recommend: true,
          response: null,
          body: "ONE STONE TO RULE THEM ALL....OH WAIT WRONG MOVIE. 7 STONES TO RULE THEM ALL. CAN'T BELIEVE THESE ARE ON SALE I'VE BEEN SEARCHING THE ENTIRE GALAXY FOR THESE.",
          date: '2021-09-24T00:00:00.000Z',
          reviewer_name: 'THANOS DUH',
          helpfulness: 16,
          photos: [],
        },
        {
          review_id: 1275105,
          rating: 5,
          summary: '',
          recommend: true,
          response: null,
          body: 'The Scanner shows that the power level of this rock is OVER 9000!',
          date: '2022-06-03T00:00:00.000Z',
          reviewer_name: 'Vegeta',
          helpfulness: 4,
          photos: [
            {
              id: 2455134,
              url: 'http://res.cloudinary.com/gc7654738/image/upload/v1654278055/FEC/ah1mf8ukx9lqu8oan9og.jpg',
            },
          ],
        },
        {
          review_id: 1276357,
          rating: 5,
          summary: 'B-bakana! K-kono power da...',
          recommend: true,
          response: null,
          body: "Oh ho? You're approaching me? Instead of running away, you're coming right to me? Even though Dr. Strange told you the secret of the Infinity Stones, like an exam student scrambling to finish the problems on an exam until the last moments before the chime?\n\nI can't beat the stones out of you without getting closer.\n\nOh ho! Then come as close as you like.",
          date: '2022-09-03T00:00:00.000Z',
          reviewer_name: 'Thanos',
          helpfulness: 1,
          photos: [
            {
              id: 2455947,
              url: 'https://res.cloudinary.com/daqlqdhlo/image/upload/v1662189266/wi6iw8lu1tgngvqwom38.jpg',
            },
          ],
        },
        {
          review_id: 1278015,
          rating: 4,
          summary: 'asdfsadfasdfasdfasdfasdfasdf',
          recommend: true,
          response: null,
          body: 'asdfasdfasdfasdfsadfsadfasdfasdfasdfasdfasdfasdfasdfasdf',
          date: '2022-12-16T00:00:00.000Z',
          reviewer_name: 'wavyj',
          helpfulness: 0,
          photos: [],
        },
        {
          review_id: 1278013,
          rating: 5,
          summary: 'BO HAS SNAPPED HALF THE UNIVERSE ',
          recommend: true,
          response: null,
          body: 'I AM THE CHOSEN ONE MUAHAHAHAHAHHAHAHAHAHAHAHAHAHAHA',
          date: '2022-12-16T00:00:00.000Z',
          reviewer_name: 'BO FO SHO ',
          helpfulness: 0,
          photos: [],
        },
        {
          review_id: 1278012,
          rating: 1,
          summary: 'Long live the man of iron',
          recommend: false,
          response: null,
          body: 'I am a lover not a fighter. Please know that!!!!!!',
          date: '2022-12-16T00:00:00.000Z',
          reviewer_name: 'Spiderman',
          helpfulness: 0,
          photos: [],
        },
        {
          review_id: 1276352,
          rating: 5,
          summary: 'WE ARE DA BOIZ',
          recommend: false,
          response: null,
          body: 'WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE \n\nWE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE \n\nWE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE WE WUZ HERE ',
          date: '2022-09-03T00:00:00.000Z',
          reviewer_name: 'BOYZ II MEN',
          helpfulness: 0,
          photos: [
            {
              id: 2455945,
              url: 'https://res.cloudinary.com/daqlqdhlo/image/upload/v1662184365/yrdwxkoencl33mk3b8c5.jpg',
            },
            {
              id: 2455946,
              url: 'https://res.cloudinary.com/daqlqdhlo/image/upload/v1662184365/pvozbv0odnii5rskgcys.jpg',
            },
          ],
        },
        {
          review_id: 841528,
          rating: 5,
          summary: 'PERFECT',
          recommend: true,
          response: null,
          body: 'I LIKE STONE VERY MUCH THEY MAKE ME HAPPY . HALF HAPPY ACTUALLY.',
          date: '2021-09-24T00:00:00.000Z',
          reviewer_name: 'LIL THANOS',
          helpfulness: 0,
          photos: [],
        },
        {
          review_id: 1275281,
          rating: 5,
          summary: 'vcx',
          recommend: true,
          response: null,
          body: 'vxsfdafdsfsdfdsfsdsdfdsgdfgdgdgfdgd vvareqvarawerewgvrwvbarewrwetwe',
          date: '2022-07-07T00:00:00.000Z',
          reviewer_name: 'cxv',
          helpfulness: 0,
          photos: [
            {
              id: 2455226,
              url: 'https://res.cloudinary.com/djtk4ap6i/image/upload/v1657163953/kbwqjjaiochoyyvildjf.jpg',
            },
          ],
        },
        {
          review_id: 1176021,
          rating: 5,
          summary: 'Best purchase ever!',
          recommend: true,
          response: null,
          body: 'Great price for an infinity stone... tastes great too.',
          date: '2022-04-11T00:00:00.000Z',
          reviewer_name: 'bob',
          helpfulness: 0,
          photos: [],
        },
        {
          review_id: 1275101,
          rating: 5,
          summary: 'Woah... is this an infinite stone...?',
          recommend: true,
          response: null,
          body: 'This looks extremely powerful... How do I achieve this power...?',
          date: '2022-06-03T00:00:00.000Z',
          reviewer_name: 'Fox',
          helpfulness: 0,
          photos: [
            {
              id: 2455132,
              url: 'http://res.cloudinary.com/dppbuevux/image/upload/v1654273316/bitdvneos5stlj7fyzgi.jpg',
            },
          ],
        },
        {
          review_id: 1275844,
          rating: 3,
          summary: "It's a good day",
          recommend: true,
          response: null,
          body: 'zszszszszszszszsz',
          date: '2022-07-22T00:00:00.000Z',
          reviewer_name: 'hulu',
          helpfulness: 0,
          photos: [],
        },
        {
          review_id: 1275843,
          rating: 3,
          summary: "It's a good day",
          recommend: true,
          response: null,
          body: 'zszszszszszszszsz',
          date: '2022-07-22T00:00:00.000Z',
          reviewer_name: 'hulu',
          helpfulness: 0,
          photos: [],
        },
        {
          review_id: 1275842,
          rating: 3,
          summary: "It's a good day",
          recommend: true,
          response: null,
          body: 'zszszszszszszszsz',
          date: '2022-07-22T00:00:00.000Z',
          reviewer_name: 'hulu',
          helpfulness: 0,
          photos: [],
        },
        {
          review_id: 1275841,
          rating: 3,
          summary: "It's a good day",
          recommend: true,
          response: null,
          body: 'zszszszszszszszsz',
          date: '2022-07-22T00:00:00.000Z',
          reviewer_name: 'hulu',
          helpfulness: 0,
          photos: [],
        },
        {
          review_id: 1275851,
          rating: 3,
          summary: "It's a good day",
          recommend: true,
          response: null,
          body: 'zszszszszszszszsz',
          date: '2022-07-22T00:00:00.000Z',
          reviewer_name: 'hulu',
          helpfulness: 0,
          photos: [],
        },
        {
          review_id: 1275850,
          rating: 3,
          summary: "It's a good day",
          recommend: true,
          response: null,
          body: 'zszszszszszszszsz',
          date: '2022-07-22T00:00:00.000Z',
          reviewer_name: 'hulu',
          helpfulness: 0,
          photos: [],
        },
        {
          review_id: 1275849,
          rating: 3,
          summary: "It's a good day",
          recommend: true,
          response: null,
          body: 'zszszszszszszszsz',
          date: '2022-07-22T00:00:00.000Z',
          reviewer_name: 'hulu',
          helpfulness: 0,
          photos: [],
        },
      ],
    },
    meta: {
      product_id: '40353',
      ratings: {
        1: '1',
        3: '7',
        4: '2',
        5: '10',
      },
      recommended: {
        false: '3',
        true: '17',
      },
      characteristics: {
        Quality: {
          id: 135252,
          value: '3.7857142857142857',
        },
      },
    },
    sortOption: 'relevant',
    filter: false,
    sort: {
      1: false, 2: false, 3: false, 4: false, 5: false,
    },
    rloading: false,
    mloading: false,
    error: null,
  },
  relatedItems: {},
};

export default intialState;
